import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body
          className={cn(
            "dark min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          <a href="api/auth/login">Login</a>
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
